# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    zone:
        - { path: ^/api/* }
    param_fetcher_listener:  true
    allowed_methods_listener:  true
    routing_loader:
        default_format: json
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: true }
            - { path: '^/', priorities: [ 'text/html', '*/*'], fallback_format: html, prefer_extension: true }
    body_converter:
        enabled: true
        validate: true
    exception:
        enabled: true
        exception_controller: 'App\Controller\Api\ExceptionController::handleException'

