version: "3.5"

services:
  app:
    build:
      context: .
      target: base-backend
    labels:
      - "application_name=php-backend-test"
    ports:
      - '11091:80/tcp' # <--- change to any free port on yours machine
    volumes:
      - ./:/var/www/html
    user: ${UID}:${GID}
    network_mode: bridge
    links:
      - db
    depends_on:
      - db
    environment:
      - 'APP_ENV=dev'
      - 'APP_DEBUG=1'
      - 'APP_SECRET=14523d2734f4c2a13137acc93ae9774a'
      - 'DATABASE_URL=mysql://admin:admin@db:3306/php-backend-test-db?serverVersion=5.7'
    command: dev ${UID}:${GID}

  db:
    image: mysql:5.7
    labels:
      - "application_name=php-backend-test"
    network_mode: bridge
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: php-backend-test-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_LOG_CONSOLE: 1
